name: ${name}
version: ${project.version}
main: ${mainClass}
authors: [royalkingkb]
api-version: 1.13

commands:
  vote:
  rules:
  map:
  seen:
  near:
    aliases: [nearby]
  help:
    aliases: [helpme, wiki, website, tutorial]
  uptime:
    aliases: [gc]
  suicide:
    aliases: [killme, endme] # I purposely did not use /kill for this one
  fly:
    permission: mcatlas.command.fly
  broadcast:
    permission: mcatlas.command.broadcast
  tp:
    aliases: [teleport, tphere, back]
    permission: mcatlas.command.tp
  speed:
    permission: mcatlas.command.speed
  entitycount:
    permission: mcatlas.command.entitycount
