name: ${name}
version: ${project.version}
main: ${mainClass}
authors: [royalkingkb]
api-version: 1.13

commands:
  vote:
  rules:
  map:
  seen:
  near:
    aliases: [nearby, nearme]
  help:
    aliases: [helpme, wiki, website, tutorial]
  border:
    aliases: [netherborder]
  uptime:
  suicide:
    aliases: [killme] # I purposely did not use /kill for this one
  fly:
    permission: mcatlas.command.fly
  broadcast:
    permission: mcatlas.command.broadcast
  tp:
    aliases: [teleport, tphere, back]
    permission: mcatlas.command.tp
  speed:
    permission: mcatlas.command.speed
  gc:
    permission: mcatlas.command.gc
  goto:
    permission: mcatlas.command.goto
  whereami:
    aliases: [donde]
    permission: mcatlas.command.whereami
  renderdistance:
    aliases: [rd]
    permission: mcatlas.command.renderdistance
  hat:
    aliases: [helmet]
    permission: mcatlas.command.hat
  entitycount:
    permission: mcatlas.command.entitycount
permissions:
  mcatlas.tamedowner:
    default: op
    description: Right click a creature to see the owner